version: "2.3"

services:
  db:
    ports:
      - "5432:5432"

  celery_broker:
    ports:
      - "5672:5672"
      - "15672:15672"

  back_worker:
    build:
      context: back
    environment:
      DEBUG: 1
    command: ["/venv/bin/celery", "-A", "master_imi", "worker", "-l", "debug"]
    volumes:
      - ./back:/app/

  back:
    build:
      context: back
    environment:
      CAS_ROOT_PROXIED_AS: http://my3a-dev.enpc.org:4200
      DEBUG: 1
      DJANGO_MANAGEPY_COLLECTSTATIC: 0
    command: "/venv/bin/python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app/

  front:
    build:
      context: front
      dockerfile: Dockerfile-dev
    ports:
      - "4200:4200"
    volumes:
      - ./front:/app/

