version: "2.3"

services:
  db:
    image: postgres:9.6
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: my3A
      POSTGRES_USER: my3A
      POSTGRES_PASSWORD: my3A

  celery_broker:
    image: rabbitmq:3.7-management
    restart: always
    volumes:
      - celery_broker-data:/var/lib/rabbitmq

  back_worker:
    image: quay.io/louistrezzini/my3a-back:${TAG:-latest}
    restart: always
    command: ["/venv/bin/celery", "-A", "master_imi", "worker", "-l", "info"]
    environment:
      DATABASE_URL: postgres://my3A:my3A@db/my3A
      CELERY_BROKER_URL: amqp://celery_broker
    depends_on:
      - celery_broker
      - db

  back:
    image: quay.io/louistrezzini/my3a-back:${TAG:-latest}
    build:
      context: back
    restart: always
    volumes:
      - back-uploads:/app/uploads
    environment:
      DATABASE_URL: postgres://my3A:my3A@db/my3A
      CELERY_BROKER_URL: amqp://celery_broker
      DJANGO_MANAGEPY_MIGRATE: 1
      DJANGO_MANAGEPY_COLLECTSTATIC: 1
    depends_on:
      - db
      - celery_broker

  front:
    image: quay.io/louistrezzini/my3a-back:${TAG:-latest}
    restart: always
    ports:
      - "9572:80"
    depends_on:
      - back

volumes:
  db-data:
  celery_broker-data:
  back-uploads:
