version: '2'

services:
  db:
    image: postgres:9.6
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: my3A
      POSTGRES_USER: my3A
      POSTGRES_PASSWORD: my3A

  back:
    build:
      context: back
    volumes:
      - back-uploads:/app/uploads
    environment:
      DATABASE_URL: postgres://my3A:my3A@db/my3A
      CELERY_BROKER_URL: amqp://celery_broker
      DJANGO_MANAGEPY_MIGRATE: 1
      DJANGO_MANAGEPY_COLLECTSTATIC: 1
    depends_on:
      - db

  front:
    build:
      context: front
    ports:
      - "8000:80"
    depends_on:
      - back

volumes:
  db-data:
  back-uploads:
